name: Setup
description: Setup Node.js, pnpm and dependencies with optimized caching

runs:
  using: 'composite'
  steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
          
      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .pnpm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
            
      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
            .next/standalone
            .next/static
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package.json') }}-${{ hashFiles('src/**/*.{js,ts,jsx,tsx}', 'app/**/*.{js,ts,jsx,tsx}', 'pages/**/*.{js,ts,jsx,tsx}') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package.json') }}-
            ${{ runner.os }}-nextjs-
            
      - name: Cache TypeScript build info
        uses: actions/cache@v4
        with:
          path: |
            **/*.tsbuildinfo
            .tsbuildinfo
          key: ${{ runner.os }}-typescript-${{ hashFiles('tsconfig.json', 'src/**/*.{ts,tsx}', 'app/**/*.{ts,tsx}', 'types/**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-typescript-
            
      - name: Cache Biome lint results
        uses: actions/cache@v4
        with:
          path: |
            .biomecache
            node_modules/.cache/biome
          key: ${{ runner.os }}-biome-${{ hashFiles('biome.json', 'src/**/*.{js,ts,jsx,tsx}', 'app/**/*.{js,ts,jsx,tsx}') }}
          restore-keys: |
            ${{ runner.os }}-biome-
            
      - name: Install dependencies
        shell: bash
        run: pnpm i --frozen-lockfile
