name = "online-draft"
main = ".open-next/worker.js"
compatibility_date = "2024-12-29"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm build:cf"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"