name = "online-draft"
compatibility_date = "2024-12-29"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm build:cf"
cwd = ""

# キャッシュファイルを除外してサイズ制限を回避
exclude = [
  ".next/cache/**",
  "build/cache/**",
  "cache/**",
  "node_modules/**",
  ".git/**",
  "*.log",
  ".wrangler/**"
]