# wrangler.toml
name = "online-draft"
main = ".open-next/worker.js"
compatibility_date = "2024-12-29"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# 環境変数があれば追加
[vars]
NEXTJS_ENV = "production"