name: Playwright setup with advanced caching
description: Setup Playwright with multi-layer caching strategy for browsers, test results, and config

runs:
  using: 'composite'
  steps:
    - name: Cache Playwright browsers
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: |
          /home/runner/.cache/ms-playwright
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-          
    - name: Install Playwright browsers if cache miss
      shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: |
        echo "⏬ Installing Playwright browsers (cache miss)..."
        pnpm exec playwright install chromium
