name: Playwright setup with advanced caching
description: Setup Playwright with multi-layer caching strategy for browsers, test results, and config

inputs:
  DATABASE_URL:
    required: true
    description: 'The database URL'
  DIRECT_URL:
    required: true
    description: 'The direct URL'
  TEST_USER_ID:
    required: true
    description: 'The test user ID'
  TEST_USER_NAME:
    required: true
    description: 'The test user name'
  TEST_USER_PASSWORD:
    required: true
    description: 'The test user password'
  TEST_USER_EMAIL:
    required: true
    description: 'The test user email'

runs:
  using: 'composite'
  steps:
    - name: Cache Playwright browsers
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: |
          /home/runner/.cache/ms-playwright
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('package.json', 'playwright.config.ts', '.storybook/test-runner.ts') }}
        restore-keys: |
          ${{ runner.os }}-playwright-${{ hashFiles('package.json') }}-
          ${{ runner.os }}-playwright-
          
    - name: Cache Playwright test results
      uses: actions/cache@v4
      with:
        path: |
          test-results
          playwright-report
        key: ${{ runner.os }}-playwright-results-${{ hashFiles('e2e/**/*.ts', 'playwright.config.ts') }}
        restore-keys: |
          ${{ runner.os }}-playwright-results-
          
    - name: Cache Playwright config
      uses: actions/cache@v4
      with:
        path: |
          .playwright
          playwright-state.json
        key: ${{ runner.os }}-playwright-config-${{ hashFiles('playwright.config.ts') }}
        restore-keys: |
          ${{ runner.os }}-playwright-config-
          
    - name: Install Playwright browsers if cache miss
      shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: |
        echo "⏬ Installing Playwright browsers (cache miss)..."
        pnpm exec playwright install --with-deps
        
    - name: Verify Playwright browsers
      shell: bash
      run: |
        echo "🔍 Verifying Playwright installation..."
        pnpm exec playwright install --with-deps chromium
        echo "✅ Playwright browsers ready"
      env:
        DATABASE_URL: ${{ inputs.DATABASE_URL }}
        DIRECT_URL: ${{ inputs.DIRECT_URL }}
        TEST_USER_ID: ${{ inputs.TEST_USER_ID }}
        TEST_USER_NAME: ${{ inputs.TEST_USER_NAME }}
        TEST_USER_PASSWORD: ${{ inputs.TEST_USER_PASSWORD }}
        TEST_USER_EMAIL: ${{ inputs.TEST_USER_EMAIL }}

